version: "3.8"

services:
  db:
    image: postgres:alpine
    ports:
      - 5433:5433
    restart: always
    environment:
      POSTGRES_DB: sms_db
#      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
